### ISSUE TITLE
是否有编译好的二进制文件已经使用说明

### ISSUE THREAD

**Issue by batxxc** [vincascm/wgcp#1]
你好，我是一名小白，我不知道该怎么使用你的客户端可否给一个详细的说明？，我看了你的主页官网的介绍，配置起来感觉非常简单，但是我没有二进制文件，我又不会编译。 然后不知道使用过程中是否有其他问题。openwrt是否可以使用？在群晖nas上该如何使用？

**Comment by batxxc** [comment]
x86

**Comment by vincascm** [comment]
只需安装好rust后运行 `cargo build --release` 即可，如果需要交叉编译，请参见 <https://github.com/cross-rs/cross>

**Comment by batxxc** [comment]
还有另外一点疑问， wgcp可以子网路由吗？ 该怎么实现？

**Comment by vincascm** [comment]
配置路由就是linux通用的方式，就和使用其它VPN一样。`ip r add ...`
